name: Compile Lists

on:
  push:
    paths:
      - sources/fqdn/allow_always.txt  # Trigger workflow when this file is updated
      - sources/fqdn/allowed_if_unspecified.txt # Trigger workflow when this file is updated
      - sources/fqdn/explicit.txt  # Trigger workflow when this file is updated
      - sources/fqdn/proxy.txt  # Trigger workflow when this file is updated
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tldextract

      - name: Generate Lists
        run: |
          python ./compile_lists.py  # Run your script to generate the lists

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./curation/unbound/all.txt ./curation/unbound/subdomain.txt ./curation/unbound/wildcard.txt
          git commit -m "Automated update of generated lists"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
